// SPDX-FileCopyrightText: 2026 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef TEXTINDEX_CREATOR_IPC_GLOBAL_H
#define TEXTINDEX_CREATOR_IPC_GLOBAL_H

#include <dfm-base/dfm_log_defines.h>

#define TEXTINDEX_CREATOR_IPC_NAMESPACE dfm_textindex_creator_ipc

#define TEXTINDEX_CREATOR_IPC_BEGIN_NAMESPACE namespace TEXTINDEX_CREATOR_IPC_NAMESPACE {
#define TEXTINDEX_CREATOR_IPC_END_NAMESPACE }
#define TEXTINDEX_CREATOR_IPC_USE_NAMESPACE using namespace TEXTINDEX_CREATOR_IPC_NAMESPACE;

TEXTINDEX_CREATOR_IPC_BEGIN_NAMESPACE
DFM_LOG_USE_CATEGORY(TEXTINDEX_CREATOR_IPC_NAMESPACE)
TEXTINDEX_CREATOR_IPC_END_NAMESPACE

#endif   // TEXTINDEX_CREATOR_IPC_GLOBAL_H
