// SPDX-FileCopyrightText: 2022 - 2023 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef DDPLUGIN_FILEMONITOR_GLOBAL_H
#define DDPLUGIN_FILEMONITOR_GLOBAL_H

#include <dfm-base/dfm_log_defines.h>

#define DDP_FILEMONITOR_NAMESPACE ddplugin_filemonitor

#define DDP_FILEMONITOR_BEGIN_NAMESPACE namespace DDP_FILEMONITOR_NAMESPACE {
#define DDP_FILEMONITOR_END_NAMESPACE }
#define DDP_FILEMONITOR_USE_NAMESPACE using namespace DDP_FILEMONITOR_NAMESPACE;

DDP_FILEMONITOR_BEGIN_NAMESPACE
DFM_LOG_USE_CATEGORY(DDP_FILEMONITOR_NAMESPACE)
DDP_FILEMONITOR_END_NAMESPACE

#endif   // DDPLUGIN_BACKGROUND_GLOBAL_H
