#!/bin/bash

#dfm-upgrade

function createUpgradeFlag(){
echo "File manager is ready to upgrade configuration."
homeDir="/home"
for user in `ls $homeDir`
do
    userDir="$homeDir/$user"
    if [ -d $userDir ]
    then
        cfgDir="$userDir/.config/deepin/dde-file-manager"
        if [ -d $cfgDir ]
        then
            echo "create flag in $cfgDir"
            touch "$cfgDir/dfm-upgraded.lock"
        else
            echo "$cfgDir is not existed, ignore it."
        fi
    fi
done
}
#end dfm-upgrade

kill_service() {
       local SERVER_NAME="$1"
	PID=$(pidof "$SERVER_NAME")

	if [ -z "$PID" ]; then
	    echo "Process $SERVER_NAME is not running."
	    return 0
	fi

	echo "Process $SERVER_NAME (PID: $PID) found. Sending SIGKILL..."
	kill -KILL "$PID"
	echo "Process $SERVER_NAME has been killed."
}


# Main function
main() {
    # Upgrade
    echo "Starting create upgrade flag"
    createUpgradeFlag

    echo "Starting postinst script execution"

    kill_service "dde-file-manager-server"
    kill_service "dde-file-manager-daemon"

    echo "Finished postinst script execution"
}

# Execute main function
main
